version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - .:/var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "kaibingoat"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "kaibingoat"
      MYSQL_DATABASE: "kaibindb"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData:
