<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- No clue what this does currently -->
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
    <!-- Logo Icon (Tab) -->
    <link rel="icon" href="images/TheHiveLogo.svg">
    <link rel="stylesheet" href="styles/style.css">

</head>
<body>
<header>
    <nav>
        <a href="index.php"><img src="images/TheHiveLogo.svg" alt="The Hive Logo"></a>
        <ul>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php">About Us</a></li>
            <li><a href="phpenhancements.php">Enhancements</a></li>
            <li><a href="manage.php">Manage</a></li>
        </ul>
        <hr>
    </nav>
</header>
